version: 2.1 
orbs: 
  node: circleci/node@3.0.0
  # heroku: circleci/heroku@0.0.10

jobs:
  backend: 
    executor:
      name: node/default
    build:
      docker:   
        # specify system properties
        - image: circleci/mysql:latest
        environment: 
          DB_HOST : $DB_NAME
          DB_URL  : $DB_HOST
          DB_USER : $DB_USER
          DB_PASS : $DB_PASSWORD      

    working_directory: ~/birdie-test

    steps:
      - checkout
      - run: cd backend && npm install
      - run: 
          name: Wait for Database Connection
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://localhost:8000 -timeout 1m
      - run: sudo apt-get install mysql-client    
      - run: cd backend && npm test
      
  front-end:
    executor:
      name: node/default

    working_directory: ~/birdie-test

    steps: 
      - checkout
      - run: cd front-end && npm install
      - run: cd front-end && npm test

workflows:
  test_my_app:
      jobs:
          - backend
          - front-end
  # heroku_deploy:
  #     jobs:
  #       - heroku/deploy-via-git