version: 2.1

jobs:
   backend:
      docker: 
      - image: circleci/node@3.0.0
      
      working_directory: ~/birdie-test
      
      steps:
      - checkout
      - run: cd backend/functions && npm install
      - run: cd backend/functions && npm format
      - run: cd backend/functions && npm lint
      - run: cd backend/functions && npm run
      - run: cd backend/functions && npm test:watch
      
   frontend:
      docker: 
       - image: circleci/node@3.0.0
       
     working_directory: ~/birdie-test
     steps: 
     - checkout: 
     - run: cd front-end && npm install
     - run: cd front-end && npm start
     - run: cd front-end && npm test
       
workflows: 
  version: 2
  concurrently: 
    jobs: 
      - backend
      - front-end
