version: 2.1 
orbs: 
  node: circleci/node@3.0.0

jobs:
  backend: 
    # docker: 
    # - image: circleci/node@3.0.0
    executor:
      name: node/default

    working_directory: ~/birdie-test

    steps:
      - checkout
      - run: cd backend/functions && npm install
      - run: cd backend/functions && npm run dev
      - run: cd backend/functions && npm test
      
  front-end:
    # docker: 
    # - image: circleci/node@3.0.0
    executor:
      name: node/default

    working_directory: ~/birdie-test

    steps: 
      - checkout
      - run: cd front-end && npm install
      - run: cd front-end && npm start
      - run: cd front-end && npm test

workflows:
  # version: 2.1
  # build:
      jobs:
          - backend
          - front-end

